[env:seeed_xiao_nrf52840_bluefruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoble_adafruit
framework = arduino

monitor_speed = 115200

lib_deps =
  adafruit/Adafruit Bluefruit nRF52 Libraries
  adafruit/Adafruit LittleFS

build_flags =
  -D GUILLEMOT_BUILD_PIO=1

